FROM node:lts AS build
WORKDIR /app

RUN npm i
RUN npm run build

FROM httpd:2.4 AS runtime
COPY --from=build /app/dist /usr/local/apache2/htdocs/
RUN apt-get update && apt-get install
CMD [ "apachectl", "-D", "FOREGROUND" ]
#ENTRYPOINT [ "/usr/local/apache2/htdocs/" ]